name: Basic Linting
on: ["push", "pull_request"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/gallium
          # Comment out the two lines of code below when running act
          # Remember to uncomment them before pushing your changes
          cache: yarn
          cache-dependency-path: package-lock.json

      - name: Frontend Code Quality
        run: |
          yarn
          yarn lint
