name: Comment by Label
on:
  pull_request:
    types:
      - labeled
      - unlabeled

jobs:
  JiraLogin:
    if: github.actor != 'dependabot[bot]' # to avoid running it on Dependabot PRs
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          # The following secrets have been setup on the Github repo
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Extract Jira Id
        id: step1
        uses: AsasInnab/regex-action@v1
        with:
          regex_pattern: 'GCE-\d+'
          regex_flags: "gim"
          search_string: "${{ github.head_ref }}"

      - name: Echo label(s)
        run: |
          echo "label(s): ${{ github.event.label.name }}"

      - name: Comment on issue (FE)
        if: ${{ github.event.label.name == 'frontend' }}
        id: jira-comment-fe
        uses: atlassian/gajira-comment@master
        with:
          issue: ${{ steps.step1.outputs.first_match }}
          # comment: ${{ github.event.pusher.name }} pushed to repository: ${{ github.event.repository.full_name }}
          comment: "@Sidharth Subramanian, please have a look (FE)"

      - name: Comment on issue (BE)
        if: ${{ github.event.label.name == 'backend' }}
        id: jira-comment-be
        uses: atlassian/gajira-comment@master
        with:
          issue: ${{ steps.step1.outputs.first_match }}
          # comment: ${{ github.event.pusher.name }} pushed to repository: ${{ github.event.repository.full_name }}
          comment: "@Sidharth Subramanian, please have a look (BE)"

      - name: Transition issue
        uses: atlassian/gajira-transition@master
        with:
          issue: ${{ steps.step1.outputs.first_match }}
          transition: "In Progress"
