name: Jira Ticket from Branch Name
on:
  workflow_call:
    inputs:
      branch_name:
        type: string
        required: true
      jira_id_regex:
        type: string
        required: true
    outputs:
      jira_id:
        description: The Jira Issue ID that can be passed to other actions
        value: ${{ jobs.GetJiraId.outputs.jira_id }}

jobs:
  GetJiraId:
    runs-on: ubuntu-latest
    outputs:
      jira_id: ${{ steps.step1.outputs.jira_id }}
    steps:
      - name: Extract Jira Id
        id: step1
        # run: |
        #   b_name=($(echo ${{ inputs.branch_name }} | tr "-"))
        #   echo "::set-output name=jira_id::${b_name[0]}'-'${b_name}[1]"
        # run: echo "::set-output name=jira_id::$(echo 'GCE-96-CI-actions-Jira' | grep -Eo 'GCE-\d+')"
        run: echo "jira_id=$(echo 'GCE-96-CI-actions-Jira' | grep -Eo 'GCE-\d+')" >> $GITHUB_ENV

      - name: Confirm Jira Id
        # run: echo "${{ steps.step1.outputs.jira_id }}"
        run: echo "${{ env.jira_id }}"
