name: "React Basic Testing"
on: ["push", "pull_request"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Setup Node"
        uses: actions/setup-node@v2
        with:
          node-version: lts/gallium
          # Comment out the two lines of code below when running act
          # Remember to uncomment them before pushing your changes
          cache: "yarn"
          cache-dependency-path: react/ci-playground/yarn.lock
      - name: "Run React Tests"
        run: |
          cd react/ci-playground
          yarn
          yarn test
